#!/usr/bin/env node
'use strict';

/*
 * build.js — scans this folder for standalone HTML pages and writes pages.js,
 * a tiny data file that index.html reads to render the homepage grid.
 *
 * Zero dependencies. Runs automatically on every Vercel deploy (see package.json /
 * vercel.json). Run it locally any time with:  node build.js
 *
 * A static page can't read its own folder in the browser, so this build step is
 * what keeps the homepage in sync. You never edit index.html by hand — just add or
 * change .html files and the list regenerates.
 *
 * Optional per-page tuning (all optional; add inside a page's <head>):
 *   <meta name="hub-title"  content="Card title">     overrides the <title>
 *   <meta name="hub-desc"   content="Short blurb">     card description
 *   <meta name="hub-order"  content="10">              sort key, lower = earlier
 *   <meta name="hub-hidden" content="true">            exclude from the homepage
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const OUTPUT = path.join(ROOT, 'pages.js');

// Files that are part of the machinery — never listed as pages.
const IGNORE = new Set(['index.html']);

// Read a <meta name="NAME" content="..."> value (attributes in either order).
function readMeta(html, name) {
  const re = new RegExp('<meta\\b[^>]*\\bname\\s*=\\s*["\']' + name + '["\'][^>]*>', 'i');
  const tag = html.match(re);
  if (!tag) return null;
  const content = tag[0].match(/\bcontent\s*=\s*["']([^"']*)["']/i);
  return content ? content[1].trim() : null;
}

function readTitle(html) {
  const m = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  return m ? m[1].replace(/\s+/g, ' ').trim() : null;
}

function collect() {
  const pages = [];

  for (const file of fs.readdirSync(ROOT)) {
    if (!file.toLowerCase().endsWith('.html')) continue;
    if (IGNORE.has(file.toLowerCase())) continue;

    const html = fs.readFileSync(path.join(ROOT, file), 'utf8');

    if ((readMeta(html, 'hub-hidden') || '').toLowerCase() === 'true') continue;

    const title = readMeta(html, 'hub-title') || readTitle(html) || file.replace(/\.html$/i, '');
    const description = readMeta(html, 'hub-desc') || readMeta(html, 'description') || '';

    const orderRaw = readMeta(html, 'hub-order');
    const orderNum = orderRaw != null && orderRaw !== '' ? Number(orderRaw) : NaN;
    const order = Number.isFinite(orderNum) ? orderNum : Infinity;

    pages.push({ file, title, description, order });
  }

  pages.sort((a, b) => {
    if (a.order !== b.order) return a.order - b.order;
    return a.title.localeCompare(b.title, undefined, { sensitivity: 'base' });
  });

  // Emit only what the homepage needs (order is a sort key, not displayed).
  return pages.map(({ file, title, description }) => ({ file, title, description }));
}

function main() {
  const pages = collect();
  const banner =
    '// AUTO-GENERATED by build.js — do not edit by hand.\n' +
    '// Regenerate with:  node build.js\n';
  const body = 'window.__PAGES__ = ' + JSON.stringify(pages, null, 2) + ';\n';
  fs.writeFileSync(OUTPUT, banner + body, 'utf8');

  console.log('build.js: wrote pages.js with ' + pages.length + ' page(s):');
  for (const p of pages) console.log('  - ' + p.file + '  ->  ' + p.title);
}

main();
