// AUTO-GENERATED by build.js — do not edit by hand.
// Regenerate with:  node build.js
window.__PAGES__ = [
  {
    "file": "interview-prep.html",
    "title": "Data Engineering Interview Prep",
    "description": ""
  },
  {
    "file": "RBB-Level5-Practice.html",
    "title": "RBB Level 5 (IT) — Practice Question Bank",
    "description": ""
  },
  {
    "file": "RBB-Level5-Notes.html",
    "title": "RBB Level 5 (IT) — Study Handbook",
    "description": ""
  },
  {
    "file": "RBB-Level6-Practice.html",
    "title": "RBB Level 6 (IT) — Practice Question Bank",
    "description": ""
  },
  {
    "file": "RBB-Level6-Notes.html",
    "title": "RBB Level 6 (IT) — Study Handbook",
    "description": ""
  }
];
